### ISSUE TITLE
404 error. Missing html pages 'advisors', 'partners', 'staff', 'acknowledgments'

### ISSUE THREAD

**Issue by shalinia** [janastu/cacim-website#8]

**Comment by salus-sage** [comment]
If the theme is going to be integrated with WordPress, then why should the
HTML pages work?

**Comment by shalinia** [comment]
I want to respond to Jai's email. Whatever we have done let him know. And
also Madhu will come to know the issues.

**Comment by shalinia** [comment]
the name of the html pages were misspelled. created new acknowledgment page.
